### ISSUE TITLE
overflow: hidden too restrictive

### ISSUE THREAD

**Issue by aarimond** [StreakYC/react-smooth-collapse#10]
I think overflow:hidden is too restrictive when expansion is finished.

I have inner components like dropdowns (position: absolute) which are forced to be enclosed within the collapse body div.

Of course its needed during transition phase, but maybe it's reasonable to turn overflow:hidden off when expansion finished?

**Comment by Macil** [comment]
The current behavior is intended, to avoid users creating content that instantly appears different as soon as the transition starts. In my experience it's too easy to design content with certain spacing or positioning CSS without realizing it will be jarringly disabled as soon as the otherwise-smooth transition runs.

It makes sense as something that could be opted out of. I'm not sure if I want a prop just for "noOverflowHiddenWhileOpen"; I'd rather do #8 than that, which would let people accomplish this.

**Comment by PeterKottas** [comment]
Just hit this one as well. Either #8 or an explicit prop would be beneficial as right now I have to hack it out with container div and child selector

**Comment by Macil** [comment]
This behavior has been added as opt-in with a prop `allowOverflowWhenOpen`.
