### ISSUE TITLE
Library creates additional wrappers

### ISSUE THREAD

**Issue by ghost** [StreakYC/react-smooth-collapse#17]
I have noticed your library adds two additional divs to the structure - one animating `height`, another setting `overflow: hidden`. This is undesired, the effect should be applied directly to the child instead of creating any new parent elements.

**Comment by Macil** [comment]
This is necessary with the current design: when animating into the open position, it needs to figure out the height of the contents. It does that by leaving the inner element as height:auto and then it measures the inner element's height. (If the inner element only uses a known fixed height, then there's not much use in using react-smooth-collapse rather than just toggling a CSS class that triggers a height transition between two fixed heights.) If there's a desired styling/appearance that having an inner element prevents, then we might investigate further.

**Comment by ghost** [comment]
Of course, added elements can and do influence layout in various way. The solution you describe sounds overarchitected for how little needs to happen in the DOM in reality, so I ended up with my own implementation.
