### ISSUE TITLE
Scrolling up automatically

### ISSUE THREAD

**Issue by charlie-ablett** [StreakYC/react-smooth-collapse#6]
Hi, I'm using your excellent library in react/redux/es6. I'm using it basically like in the example, but saving the collapsed state for each entity in the redux store. When it re-renders, it scrolls me to the top (on Chromium and Firefox) and it's a showstopper.

```javascript
  renderFileList(fileList) {
    let { entity } = this.props;
    let collapsed = entity.file_list_collapse;
    return(
      <SmoothCollapse expanded={!collapsed}>
        {fileList.map( file =>
          <li key={file.path} className="file-list-item monospace">
            <span className="fa fa-hand-o-right small-info"/>
            {file.path}
          </li>)}
      </SmoothCollapse>
    );
  }

<a href="#" onClick={e => this.handleToggle(e, entity.isCollapsed)}>Toggle</a>
// (handleToggle fires off the redux action to change isCollapsed)
```

Can you tell me why this is happening? Am I doing something wrong? How to stop it from doing that? Thanks!

**Comment by Macil** [comment]
The issue is that the user is clicking a link with href set to "#". (If you remove the onClick handler or react-smooth-collapse entirely, you'll still see this behavior.) Here's a few possible solutions I recommend.

* You can make the button be a styled span. Make sure to use the tabindex property so that it's focusable, and the role attribute so that accessibility software knows that it's a button. Use CSS to style the className to look like a link button.

```
<span className="linkButton" role="button" tabindex="0" onClick={e => this.handleToggle(e, entity.isCollapsed)}>Toggle</span>
```

* You can make the button be a styled button. You don't have to mess with the role and tabindex properties, but if you want it to look like a link then it takes a bit more CSS (`border:none;background:none;` makes it look like regular text).

```
<button className="linkButton" onClick={e => this.handleToggle(e, entity.isCollapsed)}>Toggle</button>
```

* You can keep it as an anchor tag and call `preventDefault()` on the event. It will prevent the page-scrolling behavior, but in other respects the element will continue to act as a link to "#": if the button is ctrl-clicked, middle-clicked, or right-clicked, then it will lead to the "#" page instead of doing its action, and when hovered over the browser will claim it's a link to "#".
