### ISSUE TITLE
Animation on absolute components

### ISSUE THREAD

**Issue by nerdymax** [StreakYC/react-smooth-collapse#7]
I noticed it doesn't work for absolute components. Do you have a plan to support it?

**Comment by Macil** [comment]
Can you give an example? I'm not sure I understand the problem.

**Comment by nerdymax** [comment]
Let's say `MyComponent` has `position: absolute` property. And when I try to use the library, it does not know the size of its child and as such, the animation doesn't work.

```javascript
<SmoothCollapse expanded={expanded} heightTransition=".1s cubic-bezier(1, 1, 0.5, 0.5)">
  <MyComponent />
</SmoothCollapse>
```

**Comment by Macil** [comment]
SmoothCollapse is implemented as a div with overflow:hidden which changes its own height down to 0 so that its children are hidden. Any position:absolute children would still be visible when the div is at height=0, so position:absolute children won't be supported.

You should be able to accomplish the effect you were going for by doing something like this with a position:absolute wrapper div and with MyComponent not being position:absolute:

```jsx
<div style={{position:'absolute'}}>
  <SmoothCollapse expanded={expanded} heightTransition=".1s cubic-bezier(1, 1, 0.5, 0.5)">
    <MyComponent />
  </SmoothCollapse>
</div>
```
