### ISSUE TITLE
Doesn't accept classNames property

### ISSUE THREAD

**Issue by Darrken** [StreakYC/react-smooth-collapse#8]
The component doesn't allow passing additional CSS classes via the className property.  This would be very useful! Allowing other props to just pass through (such as aria attributes) would be very nice as well.

**Comment by PeterKottas** [comment]
Sounds good to me as well.

**Comment by Macil** [comment]
I've been against this because you can achieve almost everything with wrapper divs, and it would practically obligate the presence of an collapsedClassName prop (or expandedClassName instead, but I like the idea of fewer class names on the "normal" expanded state). Maybe a transitioningClassName prop too. People can just use matching transition rules between `.normalClassName` and `.normalClassName.collapsedClassName`, but it can be a little repetitive. If the new props don't enable anything that wrapper divs couldn't, I'm more inclined toward the more minimal API.

Additionally, letting people style the element directly opens room for people to accidentally put rules on the element itself that override the CSS that react-smooth-collapse now uses or uses in a future version. Letting people style the element directly greatly increases the API-surface that has to be kept stable. But tbh react-smooth-collapse hasn't needed any CSS changes in a long while, so that concern is more diminished.

Though #10 shows a legitimate reason to override one of react-smooth-collapse's own rules, which is something I hadn't really considered before, so className+collapsedClassName(+transitioningClassName?) props are sounding better now.

**Comment by Macil** [comment]
A `className` prop has been added in 1.4.0. I've held back for now on adding a general rest-props-pass-through since that could conflict with future possibilities of letting tools like Flow detect when unknown props are passed to react-smooth-collapse, and it seems like most use-cases can be addressed with wrapper divs or the current props now.
